name: Clojure CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt update -y && sudo apt install -y gpg sudo wget curl
          sudo install -dm 755 /etc/apt/keyrings
          wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null
          echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
          sudo apt update
          sudo apt install -y mise
      - name: Run tests
        run: |
          mise install
          bb test
