name: Clojure CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: curl https://mise.jdx.dev/mise-latest-linux-x64 > ~/.local/bin/mise && chmod +x ~/.local/bin/mise && eval "$(mise activate bash)" && mise install
      - name: Run tests
        run: bb test
