name: Clojure CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testcontainer:
          - quay.io/tembo/pg15-pgmq
          - quay.io/tembo/pg16-pgmq
          - quay.io/tembo/pg17-pgmq
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Run tests
        env:
          TEST_CONTAINER: ${{ matrix.testcontainer }}
        run: |
          bb test coverage
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.testcontainer == 'quay.io/tembo/pg17-pgmq' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rlperez/pgmq-clj
          files: target/coverage/codecov.json
