name: Clojure CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install rlwrap
        run: sudo apt-get update && sudo apt-get install -y rlwrap
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Run tests
        run: |
          bb test
